spring:
  application:
    name: constructora-reactiva
  r2dbc:
    url: r2dbc:postgresql://localhost:43216/constructora_db
    username: constructora_user
    password: constructora_password
  sql:
    init:
      mode: never # Crea el schema a partir de archivo schema.sql -> never no crea el schema
      schema-locations: classpath:schema.sql
      # Opciones para mode 'always/never'
      # schema-locations: classpath:schema.sql # Deshabilitar esta linea si se establece el mode en always para crear las tablas a partir del archivo schema.sql