project(':infra-db-adapter') {

    apply plugin: 'org.springframework.boot'

    dependencies {
        implementation project(':domain-model')
        implementation project(':domain-ports')

        implementation 'org.springframework.boot:spring-boot-starter-data-r2dbc'

        runtimeOnly 'org.postgresql:r2dbc-postgresql'
        runtimeOnly 'org.postgresql:postgresql'
    }
}
